apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-k8s-practice-app
  namespace: prod
  labels:
    app: prod-k8s-practice-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-k8s-practice-app
  template:
    metadata:
      labels:
        app: prod-k8s-practice-app
    spec:
      restartPolicy: Always
      containers:
      - name: prod-k8s-practice-app
        image: k8s-practice-app
        imagePullPolicy: IfNotPresent
        env:
          - name: ENVIRONMENT
            value: prod
          - name: NAME
            value: Michelangelo
        ports:
          - containerPort: 80
            name: server
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: server
