kind: Service
apiVersion: v1
metadata:
  name: {{ include "k8s-practice-app.fullname" . }}
  namespace: {{ .Values.environment }}
  labels:
    app: {{ include "k8s-practice-app.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "k8s-practice-app.fullname" . }}
  ports:
    - name: server
      protocol: TCP
      port:  {{ .Values.service.port }}
      targetPort: server
