kind: Service
apiVersion: v1
metadata:
  name: dev-k8s-practice-app
  namespace: dev
  labels:
    app: dev-k8s-practice-app
spec:
  type: ClusterIP
  selector:
    app: dev-k8s-practice-app
  ports:
    - name: server
      protocol: TCP
      port:  80
      targetPort: server
