apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmrelease-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mdagost/k8s-practice.git
    path: helmrelease/manifests/prod/
  destination:
    server: https://kubernetes.default.svc