apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-only-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mdagost/k8s-practice.git
    path: k8s-only/manifests/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
