apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: prod

namePrefix: prod-helmrelease-kustomize-k8s-practice-app

patches:
- path: helmrelease-patch.yaml
